---
jobs:
- name: run-forever-1
  public: true
  plan:
  - task: never-die
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: /bin/bash
        args:
          - -c
          - echo 'May I never die'; while true; do sleep 1; done

- name: run-forever-2
  public: true
  plan:
  - task: never-die
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: /bin/bash
        args:
        - -c
        - echo 'May I never die'; while true; do sleep 1; done
